#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#MISE description="Run end-to-end tests"
#MISE depends=["build:dev"]
#MISE dir="tests/e2e"
set -euo pipefail

export PYLON_BINARY="${MISE_PROJECT_ROOT}/build/pylon"
go test -v -race -timeout 180s ./...
