# SPDX-License-Identifier: GPL-3.0-or-later
name: Release

on:
  push:
    branches: [master]
    paths-ignore:
      - 'client/**'
      - 'docs/**'
      - 'tests/**'

permissions:
  contents: write

jobs:
  tag:
    name: Create Version Tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Bump version and create tag
        id: tag_version
        uses: Work-Fort/github-tag-action@v6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          release_branches: master
          tag_prefix: v
